site_name: Neko Note
site_author: Core2002
repo_url: https://github.com/Core2002/neko_note
repo_name: Core2002/neko_note
copyright: Copyright &copy; 2018 Core2002
site_description: The markdown note book.
theme:
  name: material
  language: zh
  font:
    text: Noto Sans
    code: JetBrains Mono
  features:
    - content.code.copy
    - content.code.select
    - content.tabs.link
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
markdown_extensions:
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - admonition
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tabbed:
      alternate_style: true
extra:
  generator: false
